# Generated by Django 3.0.5 on 2020-05-04 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspaperpost_show_in_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaperpost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='news.Fact'),
        ),
    ]
