# Generated by Django 3.0.5 on 2020-05-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200504_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaperpost',
            name='post',
        ),
        migrations.AddField(
            model_name='newspaperpost',
            name='fact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact', to='news.Fact'),
        ),
    ]
