# Generated by Django 3.0.5 on 2020-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200504_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=False),
        ),
    ]
